/*
 * Copyright (c) 2026, Oracle and/or its affiliates.
 *
 * Licensed under the Universal Permissive License Version 1.0 as shown at
 * https://oss.oracle.com/licenses/upl/
 */
package com.oracle.database.selectai.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;

/**
 * Attribute payload for creating or updating a Select AI vector index.
 * <p>
 * Vector-index attributes configure the source content, credential, Select AI
 * profile, text chunking, retrieval behavior, vector configuration, and other
 * settings used by Select AI for retrieval-augmented generation (RAG).
 * <p>
 * For complete runnable sample sources that build
 * {@code VectorIndexAttributes}, see
 * <a href="{@docRoot}/src-html/com/oracle/database/selectai/samples/vectorindex/CreateVectorIndexSample.html">
 * CreateVectorIndexSample source</a> and
 * <a href="{@docRoot}/src-html/com/oracle/database/selectai/samples/vectorindex/UpdateVectorIndexAttributesSample.html">
 * UpdateVectorIndexAttributesSample source</a>.
 *
 * <p>
 * The SDK performs basic, deterministic validation and normalization where
 * the constraint is part of the Java API contract. Blank string values are
 * normalized to {@code null}. The SDK also prevents database-managed
 * attributes from being supplied where they are not allowed. In particular,
 * {@code pipeline_name} is generated by Oracle Database for a vector index
 * and cannot be specified when using the create builder; attempting to set it
 * results in an {@link IllegalArgumentException}.
 *
 * <p>
 * The SDK does not duplicate provider-specific, database-version-specific,
 * value-range, or other database-side semantic validation. These validations
 * are delegated to {@code DBMS_CLOUD_AI} and Oracle Database. Therefore, an
 * attribute value accepted by the SDK may still be rejected by the database
 * based on the selected profile, vector provider, database version, or other
 * database-side requirements.
 *
 * <p>
 * Use {@link #builder()} when constructing attributes for vector-index
 * creation and {@link #updateBuilder()} when constructing attributes for
 * {@code DBMS_CLOUD_AI.UPDATE_VECTOR_INDEX}. Attributes are included in the
 * generated payload only when explicitly set by the caller.
 *
 * @see <a href="https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/dbms-cloud-ai-package.html#GUID-CB37AB86-B625-4798-A3F4-8DD6DBA8B491">
 *      DBMS_CLOUD_AI.CREATE_VECTOR_INDEX procedure</a>
 * @see <a href="https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/select-ai-retrieval-augmented-generation.html">
 *      Select AI with Retrieval Augmented Generation</a>
 */
public final class VectorIndexAttributes {

    /** Size of text chunks loaded into the vector store. */
    private final Integer chunkSize;
    /** Overlap between adjacent text chunks. */
    private final Integer chunkOverlap;
    /** Whether Select AI should include source citations. */
    private final Boolean enableSources;
    /** Object storage or file location containing source documents. */
    private final String location;
    /** Number of matches returned for retrieval. */
    private final Integer matchLimit;
    /** Credential name used to read object storage content. */
    private final String objectStorageCredentialName;
    /** DBMS_CLOUD_PIPELINE pipeline name for update/read payloads. */
    private final String pipelineName;
    /** Name of the AI profile which is used for
     embedding source data and user prompts */
    private final String profileName;
    /** Refresh interval in minutes. */
    private final Integer refreshRate;
    /** Similarity threshold for retrieved matches. */
    private final Double similarityThreshold;
    /** Vector distance metric such as COSINE. */
    private final String vectorDistanceMetric;
    /** Vector database provider such as oracle. */
    private final String vectorDbProvider;
    /** Embedding vector dimension when explicitly configured. */
    private final Integer vectorDimension;
    /** Vector table name backing the index. */
    private final String vectorTableName;


    private VectorIndexAttributes(Builder builder) {
        this.chunkSize = builder.chunkSize;
        this.chunkOverlap = builder.chunkOverlap;
        this.enableSources = builder.enableSources;
        this.location = builder.location;
        this.matchLimit = builder.matchLimit;
        this.objectStorageCredentialName = builder.objectStorageCredentialName;
        this.pipelineName = builder.pipelineName;
        this.profileName = builder.profileName;
        this.refreshRate = builder.refreshRate;
        this.similarityThreshold = builder.similarityThreshold;
        this.vectorDistanceMetric = builder.vectorDistanceMetric;
        this.vectorDbProvider = builder.vectorDbProvider;
        this.vectorDimension = builder.vectorDimension;
        this.vectorTableName = builder.vectorTableName;
    }

    /**
     * Creates a builder for vector-index create payloads.
     * <p>
     * The builder does not inject database default values. Attributes are
     * included in the generated JSON only when explicitly set by the caller.
     * Database-side validation of required and semantically valid attributes is
     * performed by Oracle Database.
     *
     * @return new builder for vector-index create attribute values
     */
    public static Builder builder() {
        return new Builder(true);
    }

    /**
     * Creates a builder for update payloads.
     * <p>
     * Unlike {@link #builder()}, this builder does not populate create-time
     * defaults such as {@code chunk_size}. Set only the attributes intended for
     * {@code DBMS_CLOUD_AI.UPDATE_VECTOR_INDEX}.
     *
     * @return new builder for vector-index update attribute values
     */
    public static Builder updateBuilder() {
        return new Builder(false);
    }

    /**
     * Returns the text chunk size.
     *
     * @return configured chunk size
     */
    public Integer getChunkSize() {
        return chunkSize;
    }

    /**
     * Returns the chunk overlap.
     *
     * @return configured chunk overlap
     */
    public Integer getChunkOverlap() {
        return chunkOverlap;
    }

    /**
     * Returns whether source citations are enabled.
     *
     * @return enable-sources flag
     */
    public Boolean getEnableSources() {
        return enableSources;
    }

    /**
     * Returns the source document location.
     *
     * @return location URI/path for source content
     */
    public String getLocation() {
        return location;
    }

    /**
     * Returns the retrieval match limit.
     *
     * @return configured match limit
     */
    public Integer getMatchLimit() {
        return matchLimit;
    }

    /**
     * Returns the credential used to read object storage content.
     *
     * @return object storage credential name
     */
    public String getObjectStorageCredentialName() {
        return objectStorageCredentialName;
    }

    /**
     * Returns the pipeline name.
     *
     * @return pipeline name, or {@code null} when unset
     */
    public String getPipelineName() {
        return pipelineName;
    }

    /**
     * Returns the associated Select AI profile name.
     *
     * @return profile name associated with this vector index
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Returns the refresh interval in minutes.
     *
     * @return refresh rate in minutes
     */
    public Integer getRefreshRate() {
        return refreshRate;
    }

    /**
     * Returns the similarity threshold.
     *
     * @return similarity threshold value
     */
    public Double getSimilarityThreshold() {
        return similarityThreshold;
    }

    /**
     * Returns the vector distance metric.
     *
     * @return vector distance metric name
     */
    public String getVectorDistanceMetric() {
        return vectorDistanceMetric;
    }

    /**
     * Returns the vector database provider.
     *
     * @return vector database provider name
     */
    public String getVectorDbProvider() {
        return vectorDbProvider;
    }

    /**
     * Returns the configured vector dimension.
     *
     * @return vector dimension, or {@code null} when unset
     */
    public Integer getVectorDimension() {
        return vectorDimension;
    }

    /**
     * Returns the vector table name.
     *
     * @return vector table name, or {@code null} when unset
     */
    public String getVectorTableName() {
        return vectorTableName;
    }

    /**
     * Serializes attributes using DBMS_CLOUD_AI snake_case JSON names.
     *
     * @return JSON representation of this VectorIndexAttributes instance
     */
    public String toJson() {
        ObjectMapper mapper = new ObjectMapper();
        try {
            mapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
            mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
            return mapper.writeValueAsString(this);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to serialize VectorIndexAttributes to JSON", e);
        }
    }

    /**
     * Builder for {@link VectorIndexAttributes}.
     */
    public static final class Builder {
        /** Whether create-time required fields must be present. */
        private final boolean createPayload;
        /** Chunk size being assembled. */
        private Integer chunkSize;
        /** Chunk overlap being assembled. */
        private Integer chunkOverlap;
        /** Source citation flag being assembled. */
        private Boolean enableSources;
        /** Source content location being assembled. */
        private String location;
        /** Match limit being assembled. */
        private Integer matchLimit;
        /** Object storage credential name being assembled. */
        private String objectStorageCredentialName;
        /** Pipeline name being assembled. */
        private String pipelineName;
        /** Profile name being assembled. */
        private String profileName;
        /** Refresh rate being assembled. */
        private Integer refreshRate;
        /** Similarity threshold being assembled. */
        private Double similarityThreshold;
        /** Vector distance metric being assembled. */
        private String vectorDistanceMetric;
        /** Vector database provider being assembled. */
        private String vectorDbProvider;
        /** Vector dimension being assembled. */
        private Integer vectorDimension;
        /** Vector table name being assembled. */
        private String vectorTableName;

        private Builder(boolean createPayload) {
            this.createPayload = createPayload;
        }

        /**
         * Sets the text chunk size.
         *
         * @param chunkSize chunk size
         * @return this builder instance
         */
        public Builder chunkSize(Integer chunkSize) {
            this.chunkSize = chunkSize;
            return this;
        }

        /**
         * Sets the overlap between text chunks.
         *
         * @param chunkOverlap chunk overlap
         * @return this builder instance
         */
        public Builder chunkOverlap(Integer chunkOverlap) {
            this.chunkOverlap = chunkOverlap;
            return this;
        }

        /**
         * Sets whether source citations are enabled.
         *
         * @param enableSources source citation flag
         * @return this builder instance
         */
        public Builder enableSources(Boolean enableSources) {
            this.enableSources = enableSources;
            return this;
        }

        /**
         * Sets the source document location.
         *
         * @param location object storage or file location
         * @return this builder instance
         */
        public Builder location(String location) {
            this.location = normalize(location);
            return this;
        }

        /**
         * Sets the retrieval match limit.
         *
         * @param matchLimit match limit
         * @return this builder instance
         */
        public Builder matchLimit(Integer matchLimit) {
            this.matchLimit = matchLimit;
            return this;
        }

        /**
         * Sets the credential used to read object storage content.
         *
         * @param objectStorageCredentialName object storage credential name
         * @return this builder instance
         */
        public Builder objectStorageCredentialName(String objectStorageCredentialName) {
            this.objectStorageCredentialName = normalize(objectStorageCredentialName);
            return this;
        }

        /**
         * Sets the pipeline name for update payloads.
         * <p>
         * {@code pipeline_name} is generated by the database during vector
         * index creation and cannot be supplied in create payloads.
         *
         * @param pipelineName DBMS_CLOUD_PIPELINE pipeline name
         * @return this builder instance
         * @throws IllegalArgumentException when used with the create builder
         */
        public Builder pipelineName(String pipelineName) {
            if (createPayload) {
                throw new IllegalArgumentException("pipelineName cannot be specified during vector index creation");
            }
            this.pipelineName = normalize(pipelineName);
            return this;
        }

        /**
         * Sets the Select AI profile used by the vector index.
         *
         * @param profileName Select AI profile name
         * @return this builder instance
         */
        public Builder profileName(String profileName) {
            this.profileName = normalize(profileName);
            return this;
        }

        /**
         * Sets the refresh interval in minutes.
         *
         * @param refreshRate refresh interval
         * @return this builder instance
         */
        public Builder refreshRate(Integer refreshRate) {
            this.refreshRate = refreshRate;
            return this;
        }

        /**
         * Sets the retrieval similarity threshold.
         *
         * @param similarityThreshold similarity threshold
         * @return this builder instance
         */
        public Builder similarityThreshold(Double similarityThreshold) {
            this.similarityThreshold = similarityThreshold;
            return this;
        }

        /**
         * Sets the vector distance metric.
         *
         * @param vectorDistanceMetric distance metric name
         * @return this builder instance
         */
        public Builder vectorDistanceMetric(String vectorDistanceMetric) {
            this.vectorDistanceMetric = normalize(vectorDistanceMetric);
            return this;
        }

        /**
         * Sets the vector database provider.
         *
         * @param vectorDbProvider vector database provider name
         * @return this builder instance
         */
        public Builder vectorDbProvider(String vectorDbProvider) {
            this.vectorDbProvider = normalize(vectorDbProvider);
            return this;
        }

        /**
         * Sets the vector dimension.
         *
         * @param vectorDimension vector dimension
         * @return this builder instance
         */
        public Builder vectorDimension(Integer vectorDimension) {
            this.vectorDimension = vectorDimension;
            return this;
        }

        /**
         * Sets the backing vector table name.
         *
         * @param vectorTableName vector table name
         * @return this builder instance
         */
        public Builder vectorTableName(String vectorTableName) {
            this.vectorTableName = normalize(vectorTableName);
            return this;
        }

        /**
         * Normalizes blank input strings to {@code null}.
         *
         * @param value value to trim
         * @return trimmed value, or {@code null} when input is null/blank
         */
        private static String normalize(String value) {
            if (value == null) {
                return null;
            }
            String trimmed = value.trim();
            return trimmed.isEmpty() ? null : trimmed;
        }

        /**
         * Builds the vector index attribute payload.
         *
         * @return immutable VectorIndexAttributes built from validated builder state
         */
        public VectorIndexAttributes build() {
            return new VectorIndexAttributes(this);
        }
    }
}
